[build]
builder = "nixpacks"
buildCommand = "composer install --optimize-autoloader --no-dev && chmod +x docker-entrypoint.sh"

[deploy]
startCommand = "./docker-entrypoint.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 